# Generated by Django 5.1.5 on 2025-01-22 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0005_aiinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_budget_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
